import '@/src/app/globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DefaultLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <div className="min-h-screen flex flex-1 flex-col md:pl-64">
        { children }
      </div>
    </div>
  );
}